package co.com.prueba;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-17T18:11:43.597-05:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "ServicioIdentificacionPlus",
                  wsdlLocation = "file:/C:/Users/john/AppData/Local/Temp/tempdir8345993573739651879.tmp/ServicioIdentificacionPlus_1.wsdl",
                  targetNamespace = "http://www.datacredito.com.co/services/ServicioIdentificacion/v1")
public class ServicioIdentificacionPlus extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.datacredito.com.co/services/ServicioIdentificacion/v1", "ServicioIdentificacionPlus");
    public final static QName ServicioIdentificacionPlusDmzHttps = new QName("http://www.datacredito.com.co/services/ServicioIdentificacion/v1", "ServicioIdentificacionPlus.dmz.https");
    public final static QName ServicioIdentificacionPlusWanHttps = new QName("http://www.datacredito.com.co/services/ServicioIdentificacion/v1", "ServicioIdentificacionPlus.wan.https");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/john/AppData/Local/Temp/tempdir8345993573739651879.tmp/ServicioIdentificacionPlus_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioIdentificacionPlus.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/john/AppData/Local/Temp/tempdir8345993573739651879.tmp/ServicioIdentificacionPlus_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioIdentificacionPlus(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioIdentificacionPlus(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioIdentificacionPlus() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServicioIdentificacionPlus(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioIdentificacionPlus(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioIdentificacionPlus(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServicioIdentificacion
     */
    @WebEndpoint(name = "ServicioIdentificacionPlus.dmz.https")
    public ServicioIdentificacion getServicioIdentificacionPlusDmzHttps() {
        return super.getPort(ServicioIdentificacionPlusDmzHttps, ServicioIdentificacion.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioIdentificacion
     */
    @WebEndpoint(name = "ServicioIdentificacionPlus.dmz.https")
    public ServicioIdentificacion getServicioIdentificacionPlusDmzHttps(WebServiceFeature... features) {
        return super.getPort(ServicioIdentificacionPlusDmzHttps, ServicioIdentificacion.class, features);
    }


    /**
     *
     * @return
     *     returns ServicioIdentificacion
     */
    @WebEndpoint(name = "ServicioIdentificacionPlus.wan.https")
    public ServicioIdentificacion getServicioIdentificacionPlusWanHttps() {
        return super.getPort(ServicioIdentificacionPlusWanHttps, ServicioIdentificacion.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioIdentificacion
     */
    @WebEndpoint(name = "ServicioIdentificacionPlus.wan.https")
    public ServicioIdentificacion getServicioIdentificacionPlusWanHttps(WebServiceFeature... features) {
        return super.getPort(ServicioIdentificacionPlusWanHttps, ServicioIdentificacion.class, features);
    }

}
