
package co.com.datacredito.services.v1.serviciolocalizacion;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-04-12T14:59:28.039-05:00
 * Generated source version: 3.2.6
 *
 */
public final class ServicioLocalizacion_ServicioLocalizacionPortDmzHttps_Client {

    private static final QName SERVICE_NAME = new QName("http://www.datacredito.com.co/services/v1/ServicioLocalizacion", "ServicioLocalizacion");

    private ServicioLocalizacion_ServicioLocalizacionPortDmzHttps_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServicioLocalizacion_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ServicioLocalizacion_Service ss = new ServicioLocalizacion_Service(wsdlURL, SERVICE_NAME);
        ServicioLocalizacion port = ss.getServicioLocalizacionPortDmzHttps();

        {
        System.out.println("Invoking consultarDatosLocalizacion...");
        co.com.datacredito.services.schema.serviciolocalizacion.v1.ConsultarDatosLocalizacion _consultarDatosLocalizacion_parameters = null;
        try {
            co.com.datacredito.services.schema.serviciolocalizacion.v1.ConsultarDatosLocalizacionResponse _consultarDatosLocalizacion__return = port.consultarDatosLocalizacion(_consultarDatosLocalizacion_parameters);
            System.out.println("consultarDatosLocalizacion.result=" + _consultarDatosLocalizacion__return);

        } catch (ServicioLocalizacionException e) {
            System.out.println("Expected exception: ServicioLocalizacionException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking customConsultarDatosLocalizacion...");
        co.com.datacredito.services.schema.serviciolocalizacion.v1.CustomConsultarDatosLocalizacion _customConsultarDatosLocalizacion_parameters = null;
        try {
            co.com.datacredito.services.schema.serviciolocalizacion.v1.CustomConsultarDatosLocalizacionResponse _customConsultarDatosLocalizacion__return = port.customConsultarDatosLocalizacion(_customConsultarDatosLocalizacion_parameters);
            System.out.println("customConsultarDatosLocalizacion.result=" + _customConsultarDatosLocalizacion__return);

        } catch (ServicioLocalizacionException e) {
            System.out.println("Expected exception: ServicioLocalizacionException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
