
package co.com.datacredito.services.v1.serviciolocalizacion;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-04-12T14:59:28.187-05:00
 * Generated source version: 3.2.6
 *
 */

public class ServicioLocalizacion_ServicioLocalizacionPortWanHttps_Server{

    protected ServicioLocalizacion_ServicioLocalizacionPortWanHttps_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ServicioLocalizacionPortWanHttpsImpl();
        String address = "https://demo-servicesesb.datacredito.com.co/wss/localizacion/services/ServicioLocalizacion";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ServicioLocalizacion_ServicioLocalizacionPortWanHttps_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
