
package co.com.datacredito.services.servicioidentificacion.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-12-18T23:21:40.484-05:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "Fault", targetNamespace = "http://ws.id.dc.com/v1")
public class Idws2Exception extends Exception {
    
    private com.dc.id.ws.v1.Fault fault;

    public Idws2Exception() {
        super();
    }
    
    public Idws2Exception(String message) {
        super(message);
    }
    
    public Idws2Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Idws2Exception(String message, com.dc.id.ws.v1.Fault fault) {
        super(message);
        this.fault = fault;
    }

    public Idws2Exception(String message, com.dc.id.ws.v1.Fault fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public com.dc.id.ws.v1.Fault getFaultInfo() {
        return this.fault;
    }
}
