package co.com.datacredito.services.servicioidentificacion.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-12-18T23:21:40.555-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "ServicioIdentificacionPlus", 
                  wsdlLocation = "file:/C:/Users/john/Documents/NetBeansProjects/testDatacredito/src/main/resources/META-INF/ServicioIdentificacionPlus.wsdl",
                  targetNamespace = "http://www.datacredito.com.co/services/ServicioIdentificacion/v1") 
public class ServicioIdentificacionPlus extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.datacredito.com.co/services/ServicioIdentificacion/v1", "ServicioIdentificacionPlus");
    public final static QName ServicioIdentificacionPlusDmzHttps = new QName("http://www.datacredito.com.co/services/ServicioIdentificacion/v1", "ServicioIdentificacionPlus.dmz.https");
    public final static QName ServicioIdentificacionPlusWanHttps = new QName("http://www.datacredito.com.co/services/ServicioIdentificacion/v1", "ServicioIdentificacionPlus.wan.https");
    public final static QName ServicioIdentificacionPlus = new QName("http://www.datacredito.com.co/services/ServicioIdentificacion/v1", "ServicioIdentificacionPlus");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/john/Documents/NetBeansProjects/testDatacredito/src/main/resources/META-INF/ServicioIdentificacionPlus.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioIdentificacionPlus.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/john/Documents/NetBeansProjects/testDatacredito/src/main/resources/META-INF/ServicioIdentificacionPlus.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioIdentificacionPlus(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioIdentificacionPlus(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioIdentificacionPlus() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioIdentificacionPlus(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioIdentificacionPlus(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioIdentificacionPlus(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServicioIdentificacion
     */
    @WebEndpoint(name = "ServicioIdentificacionPlus.dmz.https")
    public ServicioIdentificacion getServicioIdentificacionPlusDmzHttps() {
        return super.getPort(ServicioIdentificacionPlusDmzHttps, ServicioIdentificacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioIdentificacion
     */
    @WebEndpoint(name = "ServicioIdentificacionPlus.dmz.https")
    public ServicioIdentificacion getServicioIdentificacionPlusDmzHttps(WebServiceFeature... features) {
        return super.getPort(ServicioIdentificacionPlusDmzHttps, ServicioIdentificacion.class, features);
    }
    /**
     *
     * @return
     *     returns ServicioIdentificacion
     */
    @WebEndpoint(name = "ServicioIdentificacionPlus.wan.https")
    public ServicioIdentificacion getServicioIdentificacionPlusWanHttps() {
        return super.getPort(ServicioIdentificacionPlusWanHttps, ServicioIdentificacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioIdentificacion
     */
    @WebEndpoint(name = "ServicioIdentificacionPlus.wan.https")
    public ServicioIdentificacion getServicioIdentificacionPlusWanHttps(WebServiceFeature... features) {
        return super.getPort(ServicioIdentificacionPlusWanHttps, ServicioIdentificacion.class, features);
    }
    /**
     *
     * @return
     *     returns ServicioIdentificacion
     */
    @WebEndpoint(name = "ServicioIdentificacionPlus")
    public ServicioIdentificacion getServicioIdentificacionPlus() {
        return super.getPort(ServicioIdentificacionPlus, ServicioIdentificacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioIdentificacion
     */
    @WebEndpoint(name = "ServicioIdentificacionPlus")
    public ServicioIdentificacion getServicioIdentificacionPlus(WebServiceFeature... features) {
        return super.getPort(ServicioIdentificacionPlus, ServicioIdentificacion.class, features);
    }

}
