
package com.dc.id.ws.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-17T18:11:43.527-05:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "Fault", targetNamespace = "http://ws.id.dc.com/v1")
public class Idws2Exception_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Fault fault;

    public Idws2Exception_Exception() {
        super();
    }

    public Idws2Exception_Exception(String message) {
        super(message);
    }

    public Idws2Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Idws2Exception_Exception(String message, Fault fault) {
        super(message);
        this.fault = fault;
    }

    public Idws2Exception_Exception(String message, Fault fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public Fault getFaultInfo() {
        return this.fault;
    }
}
